# This file was auto generated by Valama 0.1.2. Do not modify it.
set(project_name "bavardage-vala")
set(bavardage-vala_VERSION "0.0.0")
set(required_pkgs
"atk {nolink}"
"cairo {nolink}"
"gdk-3.0 {nolink}"
"gdk-pixbuf-2.0 {nolink}"
"gio-2.0"
"glib-2.0"
"gobject-2.0"
"gtk+-3.0"
"pango {nolink}"
"pangocairo {nolink}"
"x11 {nolink}"
)
set(srcfiles
"src/Config.vala"
"src/main.vala"
)
set(vapifiles
"vapi/config.vapi"
)
